spring:
  application:
    name: Benchmarker Admin Server
server:
  port: 5000
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://bm-data-eureka-server.sa-east-1.elasticbeanstalk.com/eureka
  instance:
    hostname: bm-data-service-admin.sa-east-1.elasticbeanstalk.com
