eureka:
  client:
    lowercaseHostname: true
    registryFetchIntervalSeconds: 5
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/
  instance:
    hostname: bm-data-eureka-server.herokuapp.com
server:
  port: 8761
spring:
  application:
    name: BenchMarker Eureka Server
  boot:
    admin:
      client:
        auto-deregistration: true
        instance:
          service-url: http://bm-data-eureka-server.herokuapp.com/
          name: BenchMarker Eureka Server
        url:
        - http://bm-data-service-admin.herokuapp.com/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'
