eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/
  instance:
    hostname: localhost
server:
  port: 5000
spring:
  application:
    name: BenchMarker Eureka Server
  boot:
    admin:
      client:
        auto-deregistration: true
        instance:
          service-url: http://localhost:8761
          name: BenchMarker Eureka Server
        url:
        - http://bm-data-service-admin.sa-east-1.elasticbeanstalk.com
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'
