server:
  port: 8082
spring:
  security:
    oauth2:
      client:
        provider:
          cfg-keycloak-provider:
            issuer-uri: http://localhost:8080/auth/realms/cfg
        registration:
          keycloak-bm-data-gateway:
            provider: cfg-keycloak-provider
            client-id: bm-data-gateway
            client-secret: 7174b51f-0bbb-4948-9087-2268772c084d
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'
  application:
    name: bm-data-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
      httpclient:
        ssl:
          useInsecureTrustManager: true
  boot:
    admin:
      client:
        auto-deregistration: true
        instance:
          service-url: http://localhost:8082/
          name: Benchmarker Gateway
          metadata:
            user: 
              name: shaddowuser
              password: H7T*$
        url:
        - http://localhost:8765
eureka:
  enableSelfPreservation: true
  registration:
    enabled: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#      non-secure-port: 80
#      secure-port: 443
  instance:
#    non-secure-port: 80
#    secure-port: 443
    hostname: localhost
    statusPageUrl: http://${eureka.hostname}:${server.port}/actuator/info
    healthCheckUrl: http://${eureka.hostname}:${server.port}/actuator/health
    homePageUrl: http://${eureka.hostname}:${server.port}/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'
springdoc:
  swagger-ui:
    urls:
    - url: http://localhost:${server.port}/bm-data-api/v3/api-docs
      name: Benchmarker Data API
