spring:
  application:
    name: bm-data-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  boot:
    admin:
      client:
        auto-deregistration: true
        instance:
          service-url: https://bm-data-gateway.herokuapp.com/
          name: Benchmarker Gateway
          metadata:
            user: 
              name: shaddowuser
              password: H7T*$
        url:
        - http://bm-data-service-admin.herokuapp.com/
eureka:
  enableSelfPreservation: true
  registration:
    enabled: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://bm-data-eureka-server.herokuapp.com/eureka
  instance:
    hostname: bm-data-gateway.herokuapp.com
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'
springdoc:
  swagger-ui:
    urls:
    - url: https://bm-data-gateway.herokuapp.com/bm-data-api/v3/api-docs
      name: Benchmarker Data API
