eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
server:
  port: 8761
spring:
  application:
    name: Benchmarker Eureka Server
  boot:
    admin:
      client:
        auto-deregistration: true
        instance:
          service-url: http://localhost:${server.port}
          name: BenchMarker Eureka Server
        url:
        - http://localhost:8765
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'
