server:
  port: 8090
spring:
  application:
    name: bm-data-api
  boot:
    admin:
      client:
        auto-deregistration: true
        instance:
          service-url: https://bm-data-api.herokuapp.com/
          name: Benchmarker Data API
          metadata:
            user: 
              name: shaddowuser
              password: H7T*$
        url:
        - http://bm-data-service-admin.herokuapp.com/
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:file:./src/main/resources/db/apitestdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
eureka:
  enableSelfPreservation: true
  registration:
    enabled: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://bm-data-eureka-server.herokuapp.com/eureka
  instance:
    non-secure-port: 80
    hostname: bm-data-api.herokuapp.com
    statusPageUrl: https://${eureka.hostname}/actuator/info
    healthCheckUrl: https://${eureka.hostname}/actuator/health
    homePageUrl: https://${eureka.hostname}/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'
