spring:
  application:
    name: bm-data-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'
springdoc:
  swagger-ui:
    urls:
    - url: https://bm-data-gateway.herokuapp.com/bm-data-api/v3/api-docs
      name: Benchmarker Data API
