server:
  port: 5000
spring:
  application:
    name: Benchmarker Data API
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:file:./src/main/resources/db/apitestdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  boot:
    admin:
      client:
        url:
        - http://localhost:8765
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'
