spring:
  application:
    name: bm-data-gateway
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'
springdoc:
  swagger-ui:
    urls:
    - url: https://bm-data-gateway.herokuapp.com/bm-data-api/v3/api-docs
      name: Benchmarker Data API
