eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
server:
  port: 5000
spring:
  application:
    name: bm-data-eureka-server
  boot:
    admin:
      client:
        url:
        - http://localhost:8765
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'
