spring:
  application:
    name: Benchmarker Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  boot:
    admin:
      client:
        auto-deregistration: true
        instance:
          service-url: https://bm-data-gateway.herokuapp.com/
          name: Benchmarker Gateway
          metadata:
            user: 
              name: shaddowuser
              password: H7T*$
        url:
        - http://bm-data-service-admin.herokuapp.com/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'
springdoc:
  swagger-ui:
    urls:
    - url: https://bm-data-gateway.herokuapp.com/bm-data-api/v3/api-docs
      name: Benchmarker Data API
